#!/bin/sh

python /home/jlinder/basenji/bin/borzoi_satg_gene_gpu_focused_ism.py -o gtex_blood_log2fc_ism_aggr -f 0 --rc 1 --shifts 0 --span 0 --tissue blood --main_tissue_ix 0 --clip_soft 384.0 --aggregate_tracks 3 --tissue_files gtex_blood_log2fc_undo_clip/scores_f0c0.h5,gtex_brain_log2fc_undo_clip/scores_f0c0.h5,gtex_liver_log2fc_undo_clip/scores_f0c0.h5,gtex_muscle_log2fc_undo_clip/scores_f0c0.h5,gtex_esophagus_log2fc_undo_clip/scores_f0c0.h5 --tissues blood,brain_cortex,liver,muscle,esophagus_muscularis --gene_file /home/jlinder/gtex_diff_expr/gtex_diff_expr_log2fc_5k.csv --max_n_genes 200 --ism_size 192 --gaussian_sigma 8 -t /home/jlinder/borzoi_v2/targets_gtex_5_tissues.txt /home/jlinder/borzoi_v2/params_pred.json /home/jlinder/borzoi_v2 /home/jlinder/gtex_diff_expr/gtex_diff_expr_log2fc_5k.gtf

python /home/jlinder/basenji/bin/borzoi_satg_gene_gpu_focused_ism.py -o gtex_brain_log2fc_ism_aggr -f 0 --rc 1 --shifts 0 --span 0 --tissue brain_cortex --main_tissue_ix 1 --clip_soft 384.0 --aggregate_tracks 3 --tissue_files gtex_blood_log2fc_undo_clip/scores_f0c0.h5,gtex_brain_log2fc_undo_clip/scores_f0c0.h5,gtex_liver_log2fc_undo_clip/scores_f0c0.h5,gtex_muscle_log2fc_undo_clip/scores_f0c0.h5,gtex_esophagus_log2fc_undo_clip/scores_f0c0.h5 --tissues blood,brain_cortex,liver,muscle,esophagus_muscularis --gene_file /home/jlinder/gtex_diff_expr/gtex_diff_expr_log2fc_5k.csv --max_n_genes 200 --ism_size 192 --gaussian_sigma 8 -t /home/jlinder/borzoi_v2/targets_gtex_5_tissues.txt /home/jlinder/borzoi_v2/params_pred.json /home/jlinder/borzoi_v2 /home/jlinder/gtex_diff_expr/gtex_diff_expr_log2fc_5k.gtf

python /home/jlinder/basenji/bin/borzoi_satg_gene_gpu_focused_ism.py -o gtex_liver_log2fc_ism_aggr -f 0 --rc 1 --shifts 0 --span 0 --tissue liver --main_tissue_ix 2 --clip_soft 384.0 --aggregate_tracks 3 --tissue_files gtex_blood_log2fc_undo_clip/scores_f0c0.h5,gtex_brain_log2fc_undo_clip/scores_f0c0.h5,gtex_liver_log2fc_undo_clip/scores_f0c0.h5,gtex_muscle_log2fc_undo_clip/scores_f0c0.h5,gtex_esophagus_log2fc_undo_clip/scores_f0c0.h5 --tissues blood,brain_cortex,liver,muscle,esophagus_muscularis --gene_file /home/jlinder/gtex_diff_expr/gtex_diff_expr_log2fc_5k.csv --max_n_genes 200 --ism_size 192 --gaussian_sigma 8 -t /home/jlinder/borzoi_v2/targets_gtex_5_tissues.txt /home/jlinder/borzoi_v2/params_pred.json /home/jlinder/borzoi_v2 /home/jlinder/gtex_diff_expr/gtex_diff_expr_log2fc_5k.gtf

python /home/jlinder/basenji/bin/borzoi_satg_gene_gpu_focused_ism.py -o gtex_muscle_log2fc_ism_aggr -f 0 --rc 1 --shifts 0 --span 0 --tissue muscle --main_tissue_ix 3 --clip_soft 384.0 --aggregate_tracks 3 --tissue_files gtex_blood_log2fc_undo_clip/scores_f0c0.h5,gtex_brain_log2fc_undo_clip/scores_f0c0.h5,gtex_liver_log2fc_undo_clip/scores_f0c0.h5,gtex_muscle_log2fc_undo_clip/scores_f0c0.h5,gtex_esophagus_log2fc_undo_clip/scores_f0c0.h5 --tissues blood,brain_cortex,liver,muscle,esophagus_muscularis --gene_file /home/jlinder/gtex_diff_expr/gtex_diff_expr_log2fc_5k.csv --max_n_genes 200 --ism_size 192 --gaussian_sigma 8 -t /home/jlinder/borzoi_v2/targets_gtex_5_tissues.txt /home/jlinder/borzoi_v2/params_pred.json /home/jlinder/borzoi_v2 /home/jlinder/gtex_diff_expr/gtex_diff_expr_log2fc_5k.gtf

python /home/jlinder/basenji/bin/borzoi_satg_gene_gpu_focused_ism.py -o gtex_esophagus_log2fc_ism_aggr -f 0 --rc 1 --shifts 0 --span 0 --tissue esophagus_muscularis --main_tissue_ix 4 --clip_soft 384.0 --aggregate_tracks 3 --tissue_files gtex_blood_log2fc_undo_clip/scores_f0c0.h5,gtex_brain_log2fc_undo_clip/scores_f0c0.h5,gtex_liver_log2fc_undo_clip/scores_f0c0.h5,gtex_muscle_log2fc_undo_clip/scores_f0c0.h5,gtex_esophagus_log2fc_undo_clip/scores_f0c0.h5 --tissues blood,brain_cortex,liver,muscle,esophagus_muscularis --gene_file /home/jlinder/gtex_diff_expr/gtex_diff_expr_log2fc_5k.csv --max_n_genes 200 --ism_size 192 --gaussian_sigma 8 -t /home/jlinder/borzoi_v2/targets_gtex_5_tissues.txt /home/jlinder/borzoi_v2/params_pred.json /home/jlinder/borzoi_v2 /home/jlinder/gtex_diff_expr/gtex_diff_expr_log2fc_5k.gtf
