#!/bin/sh

borzoi_satg_gene_focused_ism.py -o saved_models/gtex_blood_log2fc_ism_aggr -f 3 -c 0 --rc --tissue blood --main_tissue_ix 0 --untransform_old --track_scale 0.01 --track_transform 0.75 --clip_soft 384.0 --aggregate_tracks 3 --tissue_files saved_models/gtex_blood_log2fc/scores_f3c0.h5,saved_models/gtex_brain_log2fc/scores_f3c0.h5,saved_models/gtex_liver_log2fc/scores_f3c0.h5,saved_models/gtex_muscle_log2fc/scores_f3c0.h5,saved_models/gtex_esophagus_log2fc/scores_f3c0.h5 --tissues blood,brain_cortex,liver,muscle,esophagus_muscularis --gene_file diff_expr/gtex_diff_expr_log2fc_5k.csv --max_n_genes 200 --ism_size 192 --gaussian_sigma 8 -t targets_gtex_5_tissues.txt params_pred.json saved_models diff_expr/gtex_diff_expr_log2fc_5k.gtf

borzoi_satg_gene_focused_ism.py -o saved_models/gtex_brain_log2fc_ism_aggr -f 3 -c 0 --rc --tissue brain_cortex --main_tissue_ix 1 --untransform_old --track_scale 0.01 --track_transform 0.75 --clip_soft 384.0 --aggregate_tracks 3 --tissue_files saved_models/gtex_blood_log2fc/scores_f3c0.h5,saved_models/gtex_brain_log2fc/scores_f3c0.h5,saved_models/gtex_liver_log2fc/scores_f3c0.h5,saved_models/gtex_muscle_log2fc/scores_f3c0.h5,saved_models/gtex_esophagus_log2fc/scores_f3c0.h5 --tissues blood,brain_cortex,liver,muscle,esophagus_muscularis --gene_file diff_expr/gtex_diff_expr_log2fc_5k.csv --max_n_genes 200 --ism_size 192 --gaussian_sigma 8 -t targets_gtex_5_tissues.txt params_pred.json saved_models diff_expr/gtex_diff_expr_log2fc_5k.gtf

borzoi_satg_gene_focused_ism.py -o saved_models/gtex_liver_log2fc_ism_aggr -f 3 -c 0 --rc --tissue liver --main_tissue_ix 2 --untransform_old --track_scale 0.01 --track_transform 0.75 --clip_soft 384.0 --aggregate_tracks 3 --tissue_files saved_models/gtex_blood_log2fc/scores_f3c0.h5,saved_models/gtex_brain_log2fc/scores_f3c0.h5,saved_models/gtex_liver_log2fc/scores_f3c0.h5,saved_models/gtex_muscle_log2fc/scores_f3c0.h5,saved_models/gtex_esophagus_log2fc/scores_f3c0.h5 --tissues blood,brain_cortex,liver,muscle,esophagus_muscularis --gene_file diff_expr/gtex_diff_expr_log2fc_5k.csv --max_n_genes 200 --ism_size 192 --gaussian_sigma 8 -t targets_gtex_5_tissues.txt params_pred.json saved_models diff_expr/gtex_diff_expr_log2fc_5k.gtf

borzoi_satg_gene_focused_ism.py -o saved_models/gtex_muscle_log2fc_ism_aggr -f 3 -c 0 --rc --tissue muscle --main_tissue_ix 3 --untransform_old --track_scale 0.01 --track_transform 0.75 --clip_soft 384.0 --aggregate_tracks 3 --tissue_files saved_models/gtex_blood_log2fc/scores_f3c0.h5,saved_models/gtex_brain_log2fc/scores_f3c0.h5,saved_models/gtex_liver_log2fc/scores_f3c0.h5,saved_models/gtex_muscle_log2fc/scores_f3c0.h5,saved_models/gtex_esophagus_log2fc/scores_f3c0.h5 --tissues blood,brain_cortex,liver,muscle,esophagus_muscularis --gene_file diff_expr/gtex_diff_expr_log2fc_5k.csv --max_n_genes 200 --ism_size 192 --gaussian_sigma 8 -t targets_gtex_5_tissues.txt params_pred.json saved_models diff_expr/gtex_diff_expr_log2fc_5k.gtf

borzoi_satg_gene_focused_ism.py -o saved_models/gtex_esophagus_log2fc_ism_aggr -f 3 -c 0 --rc --tissue esophagus_muscularis --main_tissue_ix 4 --untransform_old --track_scale 0.01 --track_transform 0.75 --clip_soft 384.0 --aggregate_tracks 3 --tissue_files saved_models/gtex_blood_log2fc/scores_f3c0.h5,saved_models/gtex_brain_log2fc/scores_f3c0.h5,saved_models/gtex_liver_log2fc/scores_f3c0.h5,saved_models/gtex_muscle_log2fc/scores_f3c0.h5,saved_models/gtex_esophagus_log2fc/scores_f3c0.h5 --tissues blood,brain_cortex,liver,muscle,esophagus_muscularis --gene_file diff_expr/gtex_diff_expr_log2fc_5k.csv --max_n_genes 200 --ism_size 192 --gaussian_sigma 8 -t targets_gtex_5_tissues.txt params_pred.json saved_models diff_expr/gtex_diff_expr_log2fc_5k.gtf
